functions

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,13 +1,13 @@
 #!/bin/bash
 USERID=$(id -u)
-VALIDATE()
-{
-if [ $1 -ne 0 ] 
-then
-echo "Display :$2"
-exit 1
-else
-echo "MYSQL SUCESS"   
+VALIDATE(){
+    if [ $1 -ne 0 ] 
+    then
+    echo "Display Failure :$2"
+    exit 1
+    else
+    echo "Display SUCCESS :$2"
+    fi
 }
 if [ $USERID -ne 0 ] 
 then
